### ISSUE TITLE
paths to other diseases than queried

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#422]
https://ui.test.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=&t=0&q=02cb5889-94ce-4551-a901-83d601332a1b

Top result is "Fluticasone propionate / 1 Path that may treat Skin Disorder" - not connecting to the EDS/vascular type in the query.
2nd result is "Celiprolol / 2 Paths that may treat Cardiovascular Disorder" - one path to cardiovascular disorder and not connecting to the query, the other path is directly to the query (so not really 2 paths to cardiovascular disorder as stated).

Several other results with variations on those two weird patterns.

**Comment by sstemann** [comment]
I think this is coming from ARAGORN, i dont see either of these results in BTE:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/866abf15-ba50-4309-a24d-cd3a9c27f982)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bc47017b-f127-465d-a436-25eefa228e16)

For these two, there are no support graphs on the edges, the analysis graph for the overall result is occurs together in literature.  I think the ARAGORN team should take a look.

https://arax.ci.transltr.io/?r=02cb5889-94ce-4551-a901-83d601332a1b

**Comment by sandrine-m** [comment]
As Gwênlyn noticed, linked with #445 but with different agents this time.

**Comment by cbizon** [comment]
I can't reproduce this one in CI.  f23f51b0-ecc4-46b9-8341-12d3ab03d3fd

Perhaps it is closable @gglusman ?

**Comment by sharatisrani** [comment]
Here's a PK: c8c2369b-a722-4985-ad42-f0be4f8a8d6d for Ehlers-Danfos
If I parsed the results right, ROBOKOP also returns for these diseases:

MONDO:0007526 - Hypertension
MONDO:0020066 - Type 1 Diabetes Mellitus:
MONDO:0011142 - Breast Carcinoma
MONDO:0007523 - Asthma
MONDO:0019567 - Obesity
MONDO:0016002 - Autism Spectrum Disorder

**Comment by sandrine-m** [comment]
RETEST today: On [CI (UI)](https://ui.ci.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=a55377bd-bfaa-4db6-a726-3aae5fedcd85), I find 500 results from ARAGORN. And can confirm other diseases are present: search for "Cemdisiran" as an example:
<img width="979" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/47ce5eeb-19bb-4d79-963e-5d73f2303e59">
**However**, looks like on [CI (ARAX)](a55377bd-bfaa-4db6-a726-3aae5fedcd85), for the same PK, I find an error from ARAGORN and the results are not easily accessible through ARAX UI. I queried ARAGORN child PK through [ARAX UI](https://arax.ci.transltr.io/?r=7723a5dc-942c-420b-81a5-ace9c9d7870f) and found out that Cemdisiran is returned:
<img width="1141" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/ac98fc91-5725-4107-9047-93409ba61993">

**Comment by sandrine-m** [comment]
Note that MolePro returns "cardovascular disorder" as well. MolePro is investigating as well if it is a known issue or not.

**Comment by cbizon** [comment]
ARAGORN is returning this because it is coming from molepro.

**Comment by sierra-moxon** [comment]
from TAQA:
This might be from MolePro, fix coming (in CI now), fix coming in TEST next week.  We think this is fixed.
If MolePro is not the source, we might have others doing the same.  Sandrine will retest this one.

**Comment by sandrine-m** [comment]
Cannot reproduce anymore in [UI CI](https://ui.ci.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=11b0c63f-3f91-4749-8339-1e27a89752f4), I double checked the KG on [ARAX UI](https://arax.ci.transltr.io/?r=0b20684d-3b24-4d69-a4d3-2c231ee223e1) and this issue is fixed. I'll close this issue but please reopen it if you have any questions!

**Comment by gglusman** [comment]
Alas it's still happening.
What drugs may treat heart disorder? ([on CI, August 12](https://ui.ci.transltr.io/results?l=Heart%20Disorder&i=MONDO:0005267&t=0&q=95f9a185-8f65-4690-85eb-315a5a0aec5a)):

![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/dd207f3a-6963-4f5b-9a6d-705df6d29ea4)

![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/14f924cb-c70e-4be6-881d-3d882fa0f72c)

**Comment by sandrine-m** [comment]
On ARAX CI it seems fixed, here the aux graph:
<img width="1143" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/fe8e0580-dc96-42a1-8d01-1fa3491a5c8a">
But I do see `biolink:disease` intermediary nodes in the response KG as well as showing non-connected pieces not linked to the disease:
<img width="1124" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/4a116e1d-949c-485f-af0c-31bfab4648b1">

**Comment by vdancik** [comment]
@gglusman, is this still an issue?

**Comment by gglusman** [comment]
@vdancik It is. See (freshly run, Sep 13) [what drugs may treat heart disease](https://ui.test.transltr.io/main/results?l=Heart%20Disorder&i=MONDO:0005267&t=0&q=5949c39f-8f96-441d-8755-d0beb984f790), 3rd result is:
Lipopolysaccharides
3 Paths that may treat Cystic Echinococcosis

**Comment by gglusman** [comment]
This issue still arises. New example: revisiting ["what drugs may treat hypotensive disorder" on 2024/1/11](https://ui.test.transltr.io/main/results?l=Hypotensive+Disorder&i=MONDO%3A0005468&t=0&r=f96fbcf4&q=62f1f551-f0ac-4423-b23a-c5e7f836e2e9).

Results go to various diseases, some of which sound related (like orthostatic hypotension, acute hypotension, postprandial hypotension), others somewhat less (like capillary hemangioma, aortic aneurysm, varicose disease).

This specific example seems to come from SemMedDB (via ARAX, I think):
<img width="1010" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/697cbe01-39e4-4769-89be-3bc7e4a281b7">

**Comment by gaurav** [comment]
This issue arises because you could end up with paths where all the paths end in subclasses of the thing queried for (e.g. you search for breast cancer but all the paths end in male breast cancer). Not clear what the correct thing for the UI to do here would be.

One possible solution would be to add this to the testing tool to report on whenever it sees a result ending in a path that's not obviously a subclass of the question node. @jh111 

Would need to retest the original examples -- @gglusman has confirmed that hypotensive disorder is still showing this issue, but are the other examples still valid? If so, Unsecret and Molpro need to clean it up.

Not a showstopper.

**Comment by gglusman** [comment]
@gaurav Several of the examples are not about subclasses.

**Comment by gglusman** [comment]
Re-tested [what drugs may treat heart disorder](https://ui.test.transltr.io/main/results?l=Heart+Disorder&i=MONDO%3A0005267&t=0&r=1e940cce&q=b753d59f-a7b8-463d-aa54-c2d92623c591) and the results with paths to Cystic Echinococcosis are still there.
Cystic Echinococcosis is not a subclass of heart disorder.

**Comment by kaiwenho** [comment]
The screenshot from the example - revisiting ["what drugs may treat hypotensive disorder" on 2024/1/11](https://ui.test.transltr.io/main/results?l=Hypotensive+Disorder&i=MONDO%3A0005468&t=0&r=f96fbcf4&q=62f1f551-f0ac-4423-b23a-c5e7f836e2e9) by @gglusman is from Unsecret. 

The edges indicating Esophageal Varices and Vasodilation disorder being subclasses of hypotensive disorder are from umls (infores:umls-metathesaurus) and semmeddb (infores:semmeddb). To be specific, the edge "UMLS:C0595862" ("Vasodilation disorder") - "biolink:subclass_of" - "UMLS:C0020649" ("Hypotension") is from RTX-KG2 whose primary knowledge source is semmeddb ("infores:semmeddb"). I include the details of the edge in 
[edge.txt](https://github.com/NCATSTranslator/Feedback/files/14014470/edge.txt). In addition, "Esophageal Varices" is a subclass of "Varicosity" which is a subclass of "Vasodilation disorder" and these edges are from RTX-KG2 whose knowledge sources are umls and semmeddb. 

If the edge _"UMLS:C0595862" ("Vasodilation disorder") - "biolink:subclass_of" - "UMLS:C0020649" ("Hypotension")_ looks suspicious, we should let RTX-KG2 KP know.

**Comment by gglusman** [comment]
>  From the OBO tree on the left-hand side of the above screenshot (of cystic echinococcosis in disease ontology), cystic echinococcosis looks like a subtype of heart disease if I understand the tree correctly.

I'm not sure how...? The OBO tree clearly shows "cystic echinococcosis" as a "parasitic infectious disease", child of "disease by infectious agent", child of "disease" - all outside the cardiovascular/heart disease branch.

**Comment by jh111** [comment]
Disease ontologies are directed acyclic graphs, so entities can have more than parent.

In this case it it's coming from liver hydatid cyst ----> secondary complication ---> hypotension (likely acute, vs chronic). Hypotension is a cardiovascular disease. It looks strange, but it's not wrong.  You asked about hypotension. And in the situation above, the treatment for the underlying disease mechanism includes treating the parasitic infection.

There's also [Cardiac hytadid cyst](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6477106/), which is a cardiac disease, but this is less common.

**Comment by kaiwenho** [comment]
> I'm not sure how...? The OBO tree clearly shows "cystic echinococcosis" as a "parasitic infectious disease", child of "disease by infectious agent", child of "disease" - all outside the cardiovascular/heart disease branch.

The OBO tree also shows "cystic echinococcosis" is the child of "heart disease", "liver disease", "bone disease", "brain disease", and "lung disease".

**Comment by gglusman** [comment]
> > I'm not sure how...? The OBO tree clearly shows "cystic echinococcosis" as a "parasitic infectious disease", child of "disease by infectious agent", child of "disease" - all outside the cardiovascular/heart disease branch.
> 
> The OBO tree also shows "cystic echinococcosis" is the child of "heart disease", "liver disease", "bone disease", "brain disease", and "lung disease".

In the screenshot above, they look like cousins. All those you list are children of "disease of anatomical entity", which is a sibling of "disease of infectious agent", under which "cystic echinococcosis" is located.

**Comment by gglusman** [comment]
> Disease ontologies are directed acyclic graphs, so entities can have more than parent.
> 
> In this case it it's coming from liver hydatid cyst ----> secondary complication ---> hypotension (likely acute, not chronic). Hypotension is a cardiovascular disease. It looks strange, but it's not wrong. You asked about hypotension. And in the situation above, the treatment for the underlying disease mechanism includes treating the parasitic infection.
> 
> There's also [Cardiac hytadid cyst](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6477106/), which is a cardiac disease, but this is less common.

That sounds very relevant, though it's indeed strange to change "X can sometimes have phenotype Y which is a subtype of Z" into "X is a Z"...

**Comment by mbrush** [comment]
> That sounds very relevant, though it's indeed strange to change "X can sometimes have phenotype Y which is a subtype of Z" into "X is a Z"...

Agreed - I don't think we want to apply this line of reasoning to classify disease hierarchies. It is worth noting that MONDO appears to agree - as it places "cystic echinococcosis" only in the infectious disease hierarchy (overwriting the multiple inheritance asserted by DOID which is one of its sources):  

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/6dd8a723-12d0-4c64-81b3-127013233689)

In my opinion MONDO should be the ONLY ontology that we use for hierarchical relationships between diseases. One of its primary goals is to ingest and correct problematic classifications from sources like DOID, such as that discussed above. If a KG like RTX-KG2 wasn't to use other information from DOID that is OK - but IMO it should not ingest/use their hierarchy.

If the presence of the DOID ontology hierarchy in RTX-KG2 is the root of this issue - perhaps the solution is to remove it (and replace in RTX-KG2 with the MONDO hierarchy if a disease classification system is needed)? @saramsey would you agree, or would this cause issues?

**Comment by saramsey** [comment]
So if we eliminate DOID-to-DOID `subclass_of` edges, that would solve the problem in RTX-KG2?

**Comment by saramsey** [comment]
Another option is to remove DOID from RTX-KG2 altogether, as @mbrush suggested. I'd first want to check to see if there are cross-ontology axioms that refer to DOID, which we would lose in the process.

**Comment by saramsey** [comment]
logged as RTX-KG2 issue 364

**Comment by saramsey** [comment]
So, RTX KG2.8.4c is now in production and RTX KG2.9.0c is now in ITRB-TEST. I'm assuming that should fix the issue?

**Comment by saramsey** [comment]
Just checking back on this, I don't think RTXteam/RTX-KG2 issue 357 fixes or addresses this issue (NCATSTranslator/Feedback issue 422). I will look into whether we can drop DOID subclass-of edges from RTX-KG2. We would have to special-case it in the code (but this could be done, I think).

**Comment by saramsey** [comment]
We are aiming to fix this in the Sprint 4 release.

**Comment by sierra-moxon** [comment]
from @saramsey's notes, applying the "Fugu" label here (Fugu == Sprint 4 on CI)

**Comment by sstemann** [comment]
> > @kaiwenho this is still happening for the original example: https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=44aa2330-0847-49e2-a8d0-84e2e4685a09 ![image](https://private-user-images.githubusercontent.com/38321826/304798538-0377c77c-dd4a-48cf-9926-7fbb61af80cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjgzNjksIm5iZiI6MTcwNzkyODA2OSwicGF0aCI6Ii8zODMyMTgyNi8zMDQ3OTg1MzgtMDM3N2M3N2MtZGQ0YS00OGNmLTk5MjYtN2ZiYjYxYWY4MGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE2Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGZmNGRjODExNmNlMWIwZjA4NDMyYmM2N2JlZDEwOTEzNzA4MzYyMzdlMmJjMDZlM2I3MWU3MThiMDE0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UffVl6YIFCKkAS3n-PR5GHB5672WSvzt8BC3GEvjwk)
> 
> @sstemann Right. This was included as [an RTX-KG2 issue](https://github.com/RTXteam/RTX-KG2/issues/357). According to the comments, it would be solved by importing a newer version (newer than 2.8.1pre) of RTX-KG2.

I'm not able to recreate this in Test https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=40660d55-64f4-4b87-aefa-5b36597ad596

I can recreate it in [Prod ](https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=8f38565a-243f-4b41-b207-9236894050ca) > free text search Stiff

@saramsey is this expected that https://github.com/RTXteam/RTX-KG2/issues/364 is resolved in CI/Test?

Re: the original ticket from @gglusman I am also not able to reproduce the issues 

Fluticasone - is not returned
Celiprolol - all one hops to EDS

I searched for "skin" and cardiovascular" free text (looking for matching nodes) and i dont see those in the results
https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome&i=MONDO:0020066&t=0&r=0&q=a61314eb-2a6f-4f89-8c20-d383bf1950c1

Can we break out what is intended for "next phase" and plan to retest "paths to other diseases than queried" in Prod with the Fugu release with the intention to close that part of this ticket?

**Comment by sstemann** [comment]
looks fixed in Prod/Fugu.  Whatever is "next phase" please move to a different ticket.
