### ISSUE TITLE
knowledge-collaboratory: meta_knowledge_graph/ endpoint in production does not respond (504 Gateway Time-out)

### ISSUE THREAD

**Issue by isbluis** [NCATSTranslator/Feedback#593]
ARAX is currently unable to expand to _knowledge-collaboratory_ in **production**, since the published endpoint (https://collaboratory-api.transltr.io/meta_knowledge_graph) times out and does not return a valid meta_knowledge_graph.

To repro:   `wget https://collaboratory-api.transltr.io/meta_knowledge_graph`

Or try via the OpenAPI page:  
https://smart-api.info/ui/89054eff6ee6d91641d278d9ffdb3993#/trapi/Get_the_meta_knowledge_graph_of_the_Nanopublication_network_meta_knowledge_graph_get

**Comment by sstemann** [comment]
@CaseyTa is this something your team can take a look at?

**Comment by CaseyTa** [comment]
@vemonet Could you please check deployments to Test and Prod? I see CI is responsive for /meta_knowledge_graph, /query, and /health, but both Test and Prod are failing with 504 gateway timeouts.

**Comment by isbluis** [comment]
Hi @CaseyTa -- I notice that the /query endpoint in **production** has returned a 504 error for about 25% of the times that ARAX has called it in the past month or so -- maybe a related issue?

![image](https://github.com/NCATSTranslator/Feedback/assets/37852256/5418a324-1c7a-464c-ac71-42801aa17dcf)

(the above is taken from: https://arax.ncats.io/devLM/kptest/  with "production" selected:)

**Comment by vemonet** [comment]
Hi, I recently fixed this time-out issue in dev and ITRB CI, as @CaseyTa mentioned it, but I don't think it was pushed to dev and prod yet

I am making the request right now

**Comment by CaseyTa** [comment]
Fixed in test and prod now. Thanks, all!

**Comment by isbluis** [comment]
A similar issue has been happening on **CI** (with a response of 502: Bad Gateway) for the past week or so:

`wget https://collaboratory-api.ci.transltr.io/meta_knowledge_graph`

![image](https://github.com/NCATSTranslator/Feedback/assets/37852256/108802ac-e3b9-47f5-ae32-eeadc96539ca)

**Comment by isbluis** [comment]
Hi @CaseyTa .  Just following up on this in anticipation of next week's Relay, as this issue is still present in CI (we've logged over 700 failures in the past 3 days).

Let me know if you need any info from our team.  Thanks!

**Comment by vemonet** [comment]
Hi @isbluis it seems like https://collaboratory-api.ci.transltr.io is permanently returning 502 Bad Gateway

I am not sure why though, the latest commit deployed on our production server don't face the same error: https://api.collaboratory.semanticscience.org/docs

**Comment by isbluis** [comment]
Hi @vemonet .  Yea, we have also had some issues in ARAX trying to get a view into what is happening in those CI instances.  I am not in ARS or configure servers, so I am of limited help in this regard.   Maybe request a bounce and see if that fixes it? (yea, the typical IT "solution" :) )  Thanks.

**Comment by isbluis** [comment]
This appears to be resolved. Closing.

**Comment by isbluis** [comment]
Hi @CaseyTa .   Just following up on this in anticipation of this week's closing of the code window, as this issue is still present in TEST (we've logged almost 3500 failures since Feb 16).

**Comment by CaseyTa** [comment]
@isbluis Thanks for the notice. ITRB were able to resolve the issue for us.

**Comment by isbluis** [comment]
Hi @CaseyTa .  It appears that the issue is still present, as ARAX keeps being unable to retrieve a meta_knowledge_graph from **TEST**, **CI**, and even sometimes **PRODUCTION** instances.   It seems that the issue is that it takes a very long time to get a response, so we just time out and move on without expanding.

As an example, you can try this on the command-line:
`time wget https://collaboratory-api.test.transltr.io/meta_knowledge_graph`
In my testing, this takes over half a minute each time:
![image](https://github.com/NCATSTranslator/Feedback/assets/37852256/69d9aa0c-144e-47e8-8e5b-ccaf9e1e21e2)

I don't know the source of the latency, but this appears specific to infores:knowledge-collaboratory .

Hope this helps!

**Comment by CaseyTa** [comment]
@vemonet Could we add a cache to the meta_knowledgegraph endpoint?

**Comment by vemonet** [comment]
Hi, everytime I check the metaKG it takes consistently 3 to 4s to answer.

But since it queries the Nanopub network endpoint (public endpoint), the time might change depending on the load


Yes, @CaseyTa you can add a cache for the meta_kg endpoint

**Comment by CaseyTa** [comment]
@vemonet Thanks, I did test the meta_kg endpoints a few weeks ago and observed response times consistently around 30 sec, but I am seeing 3-5 sec response times right now. Will see if we can get caching added in this or next sprint cycle.

**Comment by CaseyTa** [comment]
We will track this issue in the Knowledge Collab repo so that we can take it off the hands of the TAQA group.

**Comment by isbluis** [comment]
This has been an issue again in _ci_ and _dev_ since about May 15.  Both other endpoints (prod, test) appear to be fine.

**Comment by isbluis** [comment]
This is currently happening in _PRODUCTION_ as of this weekend.  Perhaps related to TRAPI 1.5 vs. 1.4?

**Comment by CaseyTa** [comment]
https://github.com/MaastrichtU-IDS/knowledge-collaboratory/pull/17 addresses this issue. Tested working in CI.

**Comment by CaseyTa** [comment]
Fixes deployed and working in ITRB-Test now.
